# Generated by Django 4.1.3 on 2023-01-09 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_userchatroom_reverse_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchatmessages',
            old_name='user',
            new_name='sent_by',
        ),
        migrations.AddField(
            model_name='userchatroom',
            name='users',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
