# Generated by Django 4.1.3 on 2023-01-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_userchatmessages_sent_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatroom',
            name='created_with',
        ),
    ]
