# Generated by Django 4.1.3 on 2023-01-09 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_remove_userchatroom_created_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmessages',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
