# Generated by Django 4.1.3 on 2023-01-18 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_userchatmessages_seen_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userchatmessages',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_messages', to='chat.seendetail'),
        ),
    ]
