# Generated by Django 4.1.3 on 2023-01-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_seendetail_alter_userchatmessages_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='seendetail',
            name='is_recieved',
            field=models.BooleanField(default=False),
        ),
    ]
