# Generated by Django 4.1.3 on 2023-01-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_seendetail_is_recieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatmessages',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='seendetail',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.userchatmessages'),
            preserve_default=False,
        ),
    ]
