# Generated by Django 4.1.3 on 2023-01-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_seendetail_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatroom',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
