# Generated by Django 4.1.3 on 2023-01-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
    ]
